-- setup_extended_types.sql
-- Create a table with advanced types supported by Oracle 23c Free

DROP TABLE TESTUSER.EXTENDED_TYPES_TEST;

CREATE TABLE TESTUSER.EXTENDED_TYPES_TEST (
    ID NUMBER PRIMARY KEY,
    -- Intervals
    YM_INTERVAL_POS INTERVAL YEAR TO MONTH,
    YM_INTERVAL_NEG INTERVAL YEAR TO MONTH,
    DS_INTERVAL_POS INTERVAL DAY TO SECOND,
    DS_INTERVAL_NEG INTERVAL DAY TO SECOND,
    -- XML
    XML_DATA XMLTYPE,
    -- JSON (Native JSON in 21c+)
    JSON_DATA JSON,
    -- BOOLEAN (23c+)
    BOOL_VAL BOOLEAN,
    -- TIMESTAMP WITH TIME ZONE
    TS_TZ TIMESTAMP WITH TIME ZONE,
    -- BLOB/CLOB
    CLOB_DATA CLOB,
    BLOB_DATA BLOB
);

INSERT INTO TESTUSER.EXTENDED_TYPES_TEST (
    ID, YM_INTERVAL_POS, YM_INTERVAL_NEG, DS_INTERVAL_POS, DS_INTERVAL_NEG, 
    XML_DATA, JSON_DATA, BOOL_VAL, TS_TZ, CLOB_DATA, BLOB_DATA
) VALUES (
    1, 
    INTERVAL '5-6' YEAR TO MONTH, 
    INTERVAL '-1-2' YEAR TO MONTH, 
    INTERVAL '3 4:5:6.789' DAY TO SECOND, 
    INTERVAL '-7 8:9:10.111' DAY TO SECOND,
    XMLTYPE('<root><item id="1">Hello</item></root>'),
    JSON('{"name": "Rust Exporter", "version": "0.1", "tags": ["fast", "safe"]}'),
    TRUE,
    TO_TIMESTAMP_TZ('2023-12-20 12:34:56 -05:00', 'YYYY-MM-DD HH24:MI:SS TZH:TZM'),
    'Detailed CLOB content here',
    HEXTORAW('DEADBEEF')
);

INSERT INTO TESTUSER.EXTENDED_TYPES_TEST (
    ID, YM_INTERVAL_POS, YM_INTERVAL_NEG, DS_INTERVAL_POS, DS_INTERVAL_NEG, 
    XML_DATA, JSON_DATA, BOOL_VAL, TS_TZ, CLOB_DATA, BLOB_DATA
) VALUES (
    2, 
    NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, NULL, NULL
);

COMMIT;
